apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: architect-business-bot-logs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "55"
spec:
  project: gitops-apps
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: alloy
    targetRevision: 1.8.1
    helm:
      values: |
        controller:
          type: deployment
          replicas: 1
        alloy:
          configMap:
            content: |
              discovery.kubernetes "pods" {
                role = "pod"
              }

              discovery.relabel "architect_business_bot" {
                targets = discovery.kubernetes.pods.targets

                rule {
                  source_labels = ["__meta_kubernetes_namespace"]
                  regex         = "architect-business-bot"
                  action        = "keep"
                }

                rule {
                  source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
                  regex         = "architect-business-bot"
                  action        = "keep"
                }

                rule {
                  source_labels = ["__meta_kubernetes_namespace"]
                  target_label  = "namespace"
                }

                rule {
                  source_labels = ["__meta_kubernetes_pod_name"]
                  target_label  = "pod"
                }

                rule {
                  source_labels = ["__meta_kubernetes_pod_container_name"]
                  target_label  = "container"
                }

                rule {
                  source_labels = ["__meta_kubernetes_pod_label_app_kubernetes_io_name"]
                  target_label  = "app"
                }

                rule {
                  target_label = "cluster"
                  replacement  = "workload-2-k3s"
                }

                rule {
                  target_label = "job"
                  replacement  = "architect-business-bot"
                }
              }

              loki.source.kubernetes "architect_business_bot" {
                targets    = discovery.relabel.architect_business_bot.output
                forward_to = [loki.write.utility.receiver]
              }

              loki.write "utility" {
                endpoint {
                  url = "https://loki.api-api-api.com/loki/api/v1/push"
                  basic_auth {
                    username = "alloy"
                    password = "architect-business-bot-loki"
                  }
                }
              }
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: alloy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

