apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: gitops-apps
  source:
    repoURL: https://github.com/anomaly51/workload-2-k3s-argocd.git
    targetRevision: main
    path: apps/cert-manager-issuers
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /spec/target/deletionPolicy
        - /spec/data/0/remoteRef/conversionStrategy
        - /spec/data/0/remoteRef/decodingStrategy
        - /spec/data/0/remoteRef/metadataPolicy
        - /spec/data/0/remoteRef/nullBytePolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
