apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsidian-livesync
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: gitops-apps
  source:
    repoURL: https://github.com/anomaly51/workload-2-k3s-argocd.git
    targetRevision: main
    path: apps/obsidian-livesync
  destination:
    server: https://kubernetes.default.svc
    namespace: obsidian-livesync
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /spec/target/deletionPolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
