apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-class-defaults
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: gitops-apps
  source:
    repoURL: https://github.com/anomaly51/workload-2-k3s-argocd.git
    targetRevision: main
    path: infrastructure/storage-classes
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
