apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-monitor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  project: gitops-apps
  source:
    repoURL: https://github.com/anomaly51/workload-2-k3s-argocd.git
    targetRevision: main
    path: apps/uptime-monitor
  destination:
    server: https://kubernetes.default.svc
    namespace: uptime-monitor
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[]?.remoteRef.conversionStrategy
        - .spec.data[]?.remoteRef.decodingStrategy
        - .spec.data[]?.remoteRef.metadataPolicy
        - .spec.data[]?.remoteRef.nullBytePolicy
        - .spec.target.deletionPolicy
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates/0/apiVersion
        - /spec/volumeClaimTemplates/0/kind
        - /spec/volumeClaimTemplates/0/status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
