apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-token
  namespace: arc-runners
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: arc-github-token
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: "shared/github"
        property: "token"
