apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: architect-business-bot-data
  namespace: architect-business-bot
  labels:
    app.kubernetes.io/name: architect-business-bot
    app.kubernetes.io/part-of: workload-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
