apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - applications/cert-manager.yaml
  - applications/external-secrets.yaml
  - applications/nfs-provisioner.yaml
  - applications/vault-store.yaml
  - applications/cert-manager-issuers.yaml
  - applications/cloudflared.yaml
  - applications/external-dns-config.yaml
  - applications/external-dns.yaml
  - applications/architect-business-bot-logs.yaml
  - applications/architect-business-bot.yaml
  - applications/hermes-agent.yaml
  - applications/obsidian-livesync.yaml
