apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-apps
  namespace: argocd
spec:
  description: Generic project for applications managed by this GitOps repository.
  sourceRepos:
    - https://github.com/anomaly51/workload-2-k3s-argocd.git
    - https://charts.jetstack.io
    - https://charts.external-secrets.io
    - https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    - https://kubernetes-sigs.github.io/external-dns/
    - https://grafana.github.io/helm-charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
