apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bot-motivation-data
  namespace: bot-motivation
  labels:
    app.kubernetes.io/name: bot-motivation
    app.kubernetes.io/part-of: workload-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
