apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-api
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.api-api-api.com`)
      priority: 1000
      services:
        - name: argocd-server
          port: 443
          scheme: https
          serversTransport: argocd-api
  tls:
    secretName: argocd-api-tls-secret
