apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: a6aaa50f-2590-4179-84f2-d0f18bce0587
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: shisha-guid.api-api-api.com
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: shisha-guid-api.api-api-api.com
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: online-shop.api-api-api.com
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: online-shop-api.api-api-api.com
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: hermes-agent.api-api-api.com
        service: http://traefik.kube-system.svc.cluster.local:80
      - hostname: vault.api-api-api.com
        service: http://192.168.1.104
      - hostname: harbor.api-api-api.com
        service: http://192.168.1.104
      - hostname: argo-workflows.api-api-api.com
        service: http://192.168.1.104
      - service: http_status:404
