apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: a6aaa50f-2590-4179-84f2-d0f18bce0587
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: shisha-guid.api-api-api.com
        service: http://192.168.1.81
      - hostname: shisha-guid-api.api-api-api.com
        service: http://192.168.1.81
      - hostname: online-shop.api-api-api.com
        service: http://192.168.1.81
      - hostname: online-shop-api.api-api-api.com
        service: http://192.168.1.81
      - hostname: hermes-agent.api-api-api.com
        service: http://192.168.1.7
      - hostname: obsidian-livesync.api-api-api.com
        service: http://192.168.1.108
      - hostname: architect-business-bot.api-api-api.com
        service: http://192.168.1.7
      - hostname: pets-void.api-api-api.com
        service: http://192.168.1.7
      - hostname: pingme-backend.api-api-api.com
        service: http://192.168.1.7
      - hostname: uptime-monitor.api-api-api.com
        service: http://192.168.1.7
      - hostname: argocd-workload-1.api-api-api.com
        service: https://192.168.1.81
        originRequest:
          noTLSVerify: true
          httpHostHeader: argocd-workload-1.api-api-api.com
      - hostname: argocd-utility.api-api-api.com
        service: https://192.168.1.108
        originRequest:
          noTLSVerify: true
          httpHostHeader: argocd-utility.api-api-api.com
      - hostname: argocd-workload-2.api-api-api.com
        service: https://192.168.1.7
        originRequest:
          noTLSVerify: true
          httpHostHeader: argocd-workload-2.api-api-api.com
      - hostname: vault.api-api-api.com
        service: http://192.168.1.108
      - hostname: harbor.api-api-api.com
        service: http://192.168.1.108
      - hostname: argo-workflows.api-api-api.com
        service: https://192.168.1.108
        originRequest:
          noTLSVerify: true
          httpHostHeader: argo-workflows.api-api-api.com
      - hostname: kibana.api-api-api.com
        service: https://192.168.1.108
        originRequest:
          noTLSVerify: true
          httpHostHeader: kibana.api-api-api.com
      - hostname: elasticsearch.api-api-api.com
        service: https://192.168.1.108
        originRequest:
          noTLSVerify: true
          httpHostHeader: elasticsearch.api-api-api.com
      - hostname: logstash.api-api-api.com
        service: https://192.168.1.108
        originRequest:
          noTLSVerify: true
          httpHostHeader: logstash.api-api-api.com
      - hostname: prometheus.api-api-api.com
        service: https://192.168.1.108
        originRequest:
          noTLSVerify: true
          httpHostHeader: prometheus.api-api-api.com
      - hostname: grafana.api-api-api.com
        service: https://192.168.1.108
        originRequest:
          noTLSVerify: true
          httpHostHeader: grafana.api-api-api.com
      - hostname: loki.api-api-api.com
        service: https://192.168.1.108
        originRequest:
          noTLSVerify: true
          httpHostHeader: loki.api-api-api.com
      - service: http_status:404
