apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - external-secret.yaml
  - argocd-ingress.yaml
  - argocd-ingressroute.yaml
  - argocd-server-transport.yaml
  - configmap.yaml
  - deployment.yaml
